import { Prisma, type ProposedActionStatus, type SourceType, type TaskPriority, type TaskStatus } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { createTaskInTx, type TaskCreateInput } from "@/server/tasks";

/**
 * Decision-handling for `ProposedAction` rows generated by briefing runs.
 *
 * - rejected/deferred: only updates the proposed action.
 * - approved: creates a durable Task in the same transaction, links the task
 *   back via `Task.approved_from_proposed_action_id`, and marks the proposal
 *   approved with `decided_at` set.
 *
 * Approval task fields default to the proposed-action `suggested_*` values.
 * Callers (the API layer) may pass `taskOverrides` to override individual
 * fields edited by the user before approval.
 */

export class ProposedActionNotFoundError extends Error {
  constructor() {
    super("Proposed action not found");
  }
}

export class ProposedActionAlreadyDecidedError extends Error {
  constructor(public readonly currentStatus: ProposedActionStatus) {
    super(`Proposed action already in status '${currentStatus}'`);
  }
}

export type ProposalDecision = "approved" | "rejected" | "deferred";

export type TaskOverrides = Partial<
  Pick<
    TaskCreateInput,
    | "title"
    | "description"
    | "status"
    | "priority"
    | "category_id"
    | "project_id"
    | "owner"
    | "due_at"
    | "source_type"
    | "source_ref"
    | "tags"
  >
>;

export type DecideProposedActionInput = {
  proposalId: string;
  decision: ProposalDecision;
  decisionReason?: string | null;
  taskOverrides?: TaskOverrides;
};

export type DecideProposedActionResult = {
  proposal: {
    id: string;
    status: ProposedActionStatus;
    decision_reason: string | null;
    decided_at: Date | null;
    approved_task_id: string | null;
  };
  task: {
    id: string;
    title: string;
    status: TaskStatus;
    priority: TaskPriority;
    category_id: string;
    project_id: string | null;
    due_at: Date | null;
    source_type: SourceType;
    source_ref: string | null;
  } | null;
};

function buildTaskInputFromProposal(
  proposal: {
    id: string;
    title: string;
    description: string | null;
    suggested_status: TaskStatus | null;
    suggested_priority: TaskPriority | null;
    suggested_category_id: string | null;
    suggested_project_id: string | null;
    suggested_owner: string | null;
    suggested_due_at: Date | null;
    suggested_source_type: SourceType | null;
    suggested_source_ref: string | null;
    suggested_tags: Prisma.JsonValue;
  },
  overrides: TaskOverrides,
): TaskCreateInput {
  const suggestedTags = Array.isArray(proposal.suggested_tags)
    ? (proposal.suggested_tags.filter((t): t is string => typeof t === "string"))
    : undefined;

  return {
    title: overrides.title ?? proposal.title,
    description: overrides.description !== undefined
      ? overrides.description
      : proposal.description,
    status: overrides.status ?? proposal.suggested_status ?? undefined,
    priority: overrides.priority ?? proposal.suggested_priority ?? undefined,
    category_id: overrides.category_id ?? proposal.suggested_category_id ?? undefined,
    project_id: overrides.project_id !== undefined
      ? overrides.project_id
      : proposal.suggested_project_id,
    owner: overrides.owner ?? proposal.suggested_owner ?? undefined,
    due_at: overrides.due_at !== undefined
      ? overrides.due_at
      : proposal.suggested_due_at?.toISOString() ?? null,
    source_type: overrides.source_type ?? proposal.suggested_source_type ?? undefined,
    source_ref: overrides.source_ref !== undefined
      ? overrides.source_ref
      : proposal.suggested_source_ref,
    tags: overrides.tags ?? suggestedTags,
    approved_from_proposed_action_id: proposal.id,
  };
}

export async function decideProposedAction(
  input: DecideProposedActionInput,
): Promise<DecideProposedActionResult> {
  return prisma.$transaction(async (tx) => {
    const proposal = await tx.proposedAction.findUnique({
      where: { id: input.proposalId },
    });
    if (!proposal) throw new ProposedActionNotFoundError();
    if (proposal.status !== "pending") {
      throw new ProposedActionAlreadyDecidedError(proposal.status);
    }

    const decisionReason = input.decisionReason ?? null;
    const decidedAt = new Date();

    if (input.decision !== "approved") {
      const updated = await tx.proposedAction.update({
        where: { id: proposal.id },
        data: {
          status: input.decision,
          decision_reason: decisionReason,
          decided_at: decidedAt,
        },
      });
      return {
        proposal: {
          id: updated.id,
          status: updated.status,
          decision_reason: updated.decision_reason,
          decided_at: updated.decided_at,
          approved_task_id: null,
        },
        task: null,
      };
    }

    // Approval path: create the durable Task, link it both ways, mark approved.
    const taskInput = buildTaskInputFromProposal(proposal, input.taskOverrides ?? {});
    const task = await createTaskInTx(tx, taskInput, "user");

    const updated = await tx.proposedAction.update({
      where: { id: proposal.id },
      data: {
        status: "approved",
        decision_reason: decisionReason,
        decided_at: decidedAt,
      },
    });

    return {
      proposal: {
        id: updated.id,
        status: updated.status,
        decision_reason: updated.decision_reason,
        decided_at: updated.decided_at,
        approved_task_id: task.id,
      },
      task: {
        id: task.id,
        title: task.title,
        status: task.status,
        priority: task.priority,
        category_id: task.category_id,
        project_id: task.project_id,
        due_at: task.due_at,
        source_type: task.source_type,
        source_ref: task.source_ref,
      },
    };
  });
}
